### ISSUE TITLE
Can't install from Cheffile

### ISSUE THREAD

**Issue by achan** [schubergphilis/letsencrypt#16]
Am I doing something wrong? I updated my Cheffile with the following:

```
cookbook "letsencrypt", "~> 0.1.4"
```

And then install the cookbooks like so: 

```
$ librarian-chef install
/Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:309:in `unpack_package!': The package archive has too many children! (
RuntimeError)
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:224:in `cache_version_uri_unpacked!'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:93:in `block in version_uri_manifest'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:381:in `memo'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:92:in `version_uri_manifest'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:88:in `version_manifest'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:54:in `version_dependencies'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:462:in `fetch_dependencies'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/manifest.rb:125:in `fetch_dependencies!'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/manifest.rb:117:in `fetched_dependencies'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/manifest.rb:81:in `dependencies'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:117:in `block in check_manifest_for_cycles'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:117:in `each'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:117:in `map'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:117:in `check_manifest_for_cycles'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:64:in `block in recursive_resolve'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:154:in `block (3 levels) in resolving_dependency_map_fi
nd_manifests'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:187:in `block in scope_checking_manifest'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:186:in `scope_checking_manifest'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:153:in `block (2 levels) in resolving_dependency_map_fi
nd_manifests'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:211:in `block in map_find'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:210:in `each'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:210:in `map_find'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:152:in `block in resolving_dependency_map_find_manifest
s'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:165:in `block (2 levels) in scope_resolving_dependency'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:179:in `block in scope_checking_manifests'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:178:in `scope_checking_manifests'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:164:in `block in scope_resolving_dependency'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:163:in `scope_resolving_dependency'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:151:in `resolving_dependency_map_find_manifests'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:62:in `recursive_resolve'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:50:in `resolve'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver.rb:23:in `resolve'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/action/resolve.rb:26:in `run'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/cli.rb:169:in `resolve!'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-chef-0.0.4/lib/librarian/chef/cli.rb:41:in `install'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-chef-0.0.4/bin/librarian-chef:7:in `<top (required)>'
        from /Users/achan/.rbenv/versions/2.1.5/bin/librarian-chef:23:in `load'
```

Any suggestions / directions? When I remove the cookbook, the others can be installed properly.

**Comment by thoutenbos** [comment]
Maybe a corrupted download? Checked the archive on the supermarket and using `tar` I was able to extract it just fine.

**Comment by achan** [comment]
Are you able to successfully install it in a brand new project?

```bash
mkdir testdir
cd testdir
echo "cookbook 'letsencrypt', '0.1.4'" > Cheffile
librarian-chef install
```

Output:

```
/Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/dependency.rb:117:in `cache_manifests!': undefined method `manifests' for []:Array (NoMethodError)
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/dependency.rb:113:in `manifests'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:152:in `block in resolving_dependency_map_find_manifests'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:165:in `block (2 levels) in scope_resolving_dependency'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:179:in `block in scope_checking_manifests'
```

Maybe I'm missing some steps? This is my first project using Librarian / chef so I apologize if it's completely unrelated...

**Comment by achan** [comment]
Are you able to install it from a brand new project?

Cheffile:
```
$ cat Cheffile
site "https://supermarket.getchef.com/api/v1"
cookbook 'letsencrypt', '0.1.4'
```

librarian-chef install output:

```
$ librarian-chef install
/Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:309:in `unpack_package!': The package archive has too many children! (RuntimeError)
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:224:in `cache_version_uri_unpacked!'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:93:in `block in version_uri_manifest'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:381:in `memo'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:92:in `version_uri_manifest'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:88:in `version_manifest'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:54:in `version_dependencies'
        from /Users/achan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:462:in `fetch_dependencies'
```

That's the only file in the directory. Maybe I'm missing some steps? It's my first project using chef/librarian so I apologize if it's completely unrelated.

**Comment by achan** [comment]
It seems to be related to librarian not being able to handle file paths that are "too long": https://github.com/applicationsonline/librarian/issues/128

I switched to Berkshelf and it seemed to install it properly.

**Comment by thoutenbos** [comment]
Looks like a bug in librarian then, so closing it here.

**Comment by glaszig** [comment]
just so you know, using git as the source worked for me:

    cookbook 'letsencrypt', '~> 0.1.6', :git => 'https://github.com/schubergphilis/letsencrypt.git'
