### ISSUE TITLE
Doesn't fail provisioning when validation fails

### ISSUE THREAD

**Issue by acoulton** [schubergphilis/letsencrypt#17]
Thanks for this cookbook.

I was just stubbing out a recipe for this on a local vagrant box, and realised that although validation fails (and there's an error in the log) the `letsencrypt_certificate` resource appears to complete successfully. I would have expected the resource and the overall chef run to fail in this case - without triggering any delayed notifications - which is generally the convention with other chef resources.

Is this intentional, and/or am I doing something wrong?

```
==> default: * letsencrypt_certificate[{name}] action create
==> default:
==> default: * file[{name} SSL key] action create_if_missing
==> default:  (up to date)
==> default:
==> default: * directory[{docroot}/.well-known/acme-challenge] action create
==> default: [2016-02-26T23:01:14+00:00] INFO: directory[{docroot}/.well-known/acme-challenge] owner changed to 0
==> default: [2016-02-26T23:01:14+00:00] INFO: directory[{docroot}/.well-known/acme-challenge] group changed to 0
==> default: [2016-02-26T23:01:14+00:00] INFO: directory[{docroot}/.well-known/acme-challenge] mode changed to 755
==> default:
==> default: - change mode from '0777' to '0755'
==> default:
==> default: - change owner from 'vagrant' to 'root'
==> default:
==> default: - change group from 'vagrant' to 'root'
==> default:
==> default: * file[{docroot}/.well-known/acme-challenge/{token}] action create
==> default: [2016-02-26T23:01:14+00:00] INFO: file[{docroot}/.well-known/acme-challenge/{token}] created file /var/www/sciswiper/current/h
docs/.well-known/acme-challenge/{token}
==> default:
==> default: - create new file {docroot}/.well-known/acme-challenge/{token}
==> default: [2016-02-26T23:01:14+00:00] INFO: file[{docroot}/.well-known/acme-challenge/{token}] updated file contents /var/www/sciswiper/
urrent/htdocs/.well-known/acme-challenge/{token}

# {skipped other resource output}

==> default: [2016-02-26T23:01:14+00:00] INFO: file[{docroot}/.well-known/acme-challenge/{token}] owner changed to 0
==> default: [2016-02-26T23:01:14+00:00] INFO: file[{docroot}/.well-known/acme-challenge/{token}] group changed to 0
==> default: [2016-02-26T23:01:14+00:00] INFO: file[{docroot}/.well-known/acme-challenge/{token}] mode changed to 644
==> default:
==> default: - change mode from '' to '0644'
==> default:
==> default: - change owner from '' to 'root'
==> default:
==> default: - change group from '' to 'root'
==> default: [2016-02-26T23:01:25+00:00] ERROR: [{name}] Validation failed for domain {name}
==> default:
==> default: * file[{name} SSL key] action nothing
==> default:  (skipped due to action :nothing)
==> default:
==> default: * directory[{docroot}/.well-known/acme-challenge] action create
==> default:  (up to date)
==> default:
==> default: * file[{docroot}/.well-known/acme-challenge/{token}] action create
==> default:  (up to date)
==> default:
==> default: * ruby_block[create certificate for {name}] action run
==> default: [2016-02-26T23:01:25+00:00] **ERROR: [{name}] Validation failed, unable to request certificate**

# {skipped other resource output}

==> default: [2016-02-26T23:01:43+00:00] INFO: letsencrypt_certificate[{name}] sending reload action to service[apache2] (delayed)
==> default: Recipe: project::app-server
==> default:
==> default: * service[apache2] action reload
==> default: [2016-02-26T23:01:43+00:00] INFO: service[apache2] reloaded
==> default:
==> default:     - reload service service[apache2]

# {skipped other resource output}

==> default: [2016-02-26T23:01:55+00:00] INFO: letsencrypt_certificate[{name}] not queuing delayed action reload on service[apache2] (delayed), as it's already been queued
==> default: [2016-02-26T23:01:55+00:00] INFO: Chef Run complete in 45.600917319 seconds
==> default: [2016-02-26T23:01:55+00:00] INFO: Skipping removal of unused files from the cache
==> default: Running handlers:
==> default: [2016-02-26T23:01:55+00:00] INFO: Running report handlers
==> default: Running handlers complete
==> default: [2016-02-26T23:01:55+00:00] INFO: Report handlers complete
==> default: Chef Client finished, 24/226 resources updated in 46.651249508 seconds
```

**Comment by thoutenbos** [comment]
Well, I guess you could see this as a bug or as a feature. There are situations where I wouldn't want a failed validation to interrupt the rest of my Chef-client run, especially if it will retry in the next run. Could be an outage at the API server for example. On the other hand I can also see the argument you are making, where you would like a hard fail instead.

Let's make it optional then? Pull request for it is welcome.

**Comment by acoulton** [comment]
Wouldn't it make sense to use Chef's existing `ignore_failure` attribute for this? This will already handle the case where the resource (hard) fails but you want the rest of the provisioning to continue. It also outputs a significantly more verbose failure message in that case than the current 1-liner, so is much less likely to be missed:

```
==> default: [2016-02-29T21:03:29+00:00] ERROR: letsencrypt_certificate[{name}] (project::ssl_certificate line 42) had an error: RuntimeError: [{name}] Validation failed for domain {domain}; ignore_failure is set, continuing
==> default:
==> default:
==> default: ================================================================================
==> default:
==> default: Error executing action `create` on resource 'letsencrypt_certificate[{name}]'
==> default:
==> default: ================================================================================
==> default:
==> default:
==> default: RuntimeError
==> default:
==> default: ------------
==> default:
==> default: [{name}] Validation failed for domain {domain}
==> default:
==> default:
==> default: Cookbook Trace:
==> default:
==> default: ---------------
==> default:
==> default: /tmp/vagrant-chef/b48bb5e008698f017c550ce2bc31bbd5/cookbooks/letsencrypt/providers/certificate.rb:87:in `block (2 levels) in class_from_file'
==> default:
==> default: /tmp/vagrant-chef/b48bb5e008698f017c550ce2bc31bbd5/cookbooks/letsencrypt/providers/certificate.rb:55:in `map'
==> default:
==> default: /tmp/vagrant-chef/b48bb5e008698f017c550ce2bc31bbd5/cookbooks/letsencrypt/providers/certificate.rb:55:in `block in class_from_file'
==> default:
==> default:
==> default: Resource Declaration:
==> default:
==> default: ---------------------
==> default:
==> default: # In /tmp/vagrant-chef/cf7bb17922a193aa22beeed5fa26aba0/cookbooks/project/recipes/ssl_certificate.rb
==> default:
==> default:
==> default:  42: letsencrypt_certificate node['project']['site']['host'] do
==> default:
==> default:  43:   action   :nothing
==> default:
==> default:  44:   crt      node['project']['ssl']['SSLCertificateFile']
==> default:
==> default:  45:   chain    node['project']['ssl']['SSLCertificateChainFile']
==> default:
==> default:  46:   key      node['project']['ssl']['SSLCertificateKeyFile']
==> default:
==> default:  47:   method   'http'
==> default:
==> default:  48:   wwwroot  node['project']['site']['docroot']
==> default:
==> default:  49:   notifies :reload, 'service[apache2]'
==> default:
==> default:  50:   ignore_failure true
==> default:
==> default:  51: end
==> default:
==> default:  52:
==> default:
==> default:
==> default: Compiled Resource:
==> default:
==> default: ------------------
==> default:
==> default: # Declared in /tmp/vagrant-chef/cf7bb17922a193aa22beeed5fa26aba0/cookbooks/project/recipes/ssl_certificate.rb:42:in `from_file'
==> default:
==> default:
==> default: letsencrypt_certificate("{name}") do
==> default:
==> default:   action [:nothing]
==> default:
==> default:   updated true
==> default:
==> default:   updated_by_last_action true
==> default:
==> default:   ignore_failure true
==> default:
==> default:   retries 0
==> default:
==> default:   retry_delay 2
==> default:
==> default:   default_guard_interpreter :default
==> default:
==> default:   declared_type :letsencrypt_certificate
==> default:
==> default:   cookbook_name :project
==> default:
==> default:   recipe_name "ssl_certificate"
==> default:
==> default:   crt "/etc/ssl/certs/{name}.crt"
==> default:
==> default:   chain "/etc/ssl/certs/{name}.ca-bundle"
==> default:       key "/etc/ssl/private/{name}.key"
==> default:       method "http"
==> default:       wwwroot "/var/www/{name}/current/htdocs"
==> default:       cn "{name}"
==> default:       owner "root"
==> default:       group "root"
==> default:     end
```

I understand the argument you make, but you could equally say the same for most chef resources - `package`, `remote_file`, `http_request`, etc - all could fail due to remote server outages / network issues etc, but it's a well established convention that they fail the chef run by default. 

IMHO this makes sense - the declarative nature of chef recipes means that you should be able to assume that if the run was successful the server is in the state described, without reviewing the sometimes hundreds of lines of output to see whether there were any problems.

**Comment by thoutenbos** [comment]
Hadn't heard about that attribute before, so with knowing that it definitely makes sense to change the error behaviour of the provider to fatal :+1:

**Comment by acoulton** [comment]
It's lurking deep in the "common functionality" bit of the chef docs past the dark places where the wild things are.....

I hadn't heard of it either, till I noticed it looking for an example of another resource that fails :grin:

I'll do you a PR.

**Comment by thoutenbos** [comment]
Super, thanks!
