### ISSUE TITLE
Validation failed,  unable to request certificate

### ISSUE THREAD

**Issue by christinedraper** [schubergphilis/letsencrypt#19]
I'm using a recipe very much based on acme-client, but with my own server name. I cannot get it to work. Every time, I get:
```
aws_instance.ciserver (remote-exec):     * ruby_block[create certificate for jenkins.aws.3wi.io] action run[2016-03-10T17:25:59+00:00] ERROR: [jenkins.aws.3wi.io] Validation failed, unable to request certificate
```
I have checked that the challenge is accessible (e.g. I can browse  http://jenkins.aws.3wi.io/.well-known/acme-challenge/NSbcKRWllRkBCtWS0Ot-C1lNOJqXQxusdNciend-g0c and get the response).  There's nothing in the nginx log. I've tried both staging and live. 

Any ideas? Been beating my head against this for a couple of days and have to admit I am stuck.

This is my nginx conf:
```
server {
  listen   80;
  server_name jenkins.aws.3wi.io;
  access_log /var/log/nginx/localhost.access.log;
  error_log /var/log/nginx/localhost.error.log;
  location / {
    default_type "text/plain";
    root   /var/www/nginx-default;
    index  index.html;
  }
}

server {
  listen   443;
  ssl    on;
  ssl_certificate    /etc/ssl/jenkins.aws.3wi.io.crt;
  ssl_certificate_key    /etc/ssl/jenkins.aws.3wi.io.key;
  server_name jenkins.aws.3wi.io;
  access_log /var/log/nginx/localhost.access.log;
  error_log /var/log/nginx/localhost.error.log;
  location / {
    root   /var/www/nginx-default;
    index  index.html;
  }
}
```
This is my recipe:
```
include_recipe 'letsencrypt'

# Generate selfsigned certificate so nginx can start
letsencrypt_selfsigned 'jenkins.aws.3wi.io' do
  crt     '/etc/ssl/jenkins.aws.3wi.io.crt'
  key     '/etc/ssl/jenkins.aws.3wi.io.key'
end

include_recipe 'nginx'

cookbook_file "#{node['nginx']['dir']}/sites-available/test" do
  source 'nginx-test.conf'
end

directory node['nginx']['default_root'] do
  owner 'root'
  group 'root'
  recursive true
end

cookbook_file "#{node['nginx']['default_root']}/index.html" do
  source 'index.html'
end

nginx_site 'test' do
  timing :immediately
end

# Request the real certificate
letsencrypt_certificate 'jenkins.aws.3wi.io' do
  fullchain '/etc/ssl/jenkins.aws.3wi.io.crt'
  chain     '/etc/ssl/jenkins.aws.3wi.io-chain.crt'
  key       '/etc/ssl/jenkins.aws.3wi.io.key'
  method    'http'
  wwwroot   node['nginx']['default_root']
  notifies  :reload, 'service[nginx]'
end
```

**Comment by thoutenbos** [comment]
Hi Christine,

Is that the real URL you posted? Are you sure there's no firewall on it? I cannot seem to reach it from my location either (timeout). If the Let's Encrypt servers also have the timeout then you would receive this error.

Best,
Thijs

**Comment by san360** [comment]
I am able to access the acme challenge over http from browser via http://nrusca-sldxxx.xxx.xxxx.net/.well-known/acme-challenge/MzHhBumVqWHuru89F9z9sFtRhkjMBn497ljTpBsn2_w. But still cookbook is failing with below error. Any idea?
 ================================================================================
 Error executing action `create` on resource 'acme_certificate[xxxx.xxxx.x.xxx]'
 ================================================================================
 
 RuntimeError
 ------------
 [xxxx.xxxx.x.xxx] Validation failed for domain xxxx.xxxx.x.xxx
 
 Cookbook Trace:
 ---------------
 /var/chef/cache/cookbooks/acme/resources/certificate.rb:112:in `block (2 levels) in class_from_file'
 /var/chef/cache/cookbooks/acme/resources/certificate.rb:87:in `map'
 /var/chef/cache/cookbooks/acme/resources/certificate.rb:87:in `block in class_from_file'
 
 Resource Declaration:
 ---------------------
 # In /var/chef/cache/cookbooks/i360/recipes/default.rb
 
 264: acme_certificate "#{site}" do
 265:     crt      "/var/certs/#{site}.crt"
 266:     key      "/var/certs/#{site}.key"
 267:     chain    "/var/certs/#{site}.pem"
 268:     notifies :restart, "service[apache2]"
 269:     wwwroot  "/var/www/html"
 270:     alt_names sans
 271: end 
 272:
