### ISSUE TITLE
undefined method `file' for Chef::Resource::RubyBlock

### ISSUE THREAD

**Issue by glaszig** [schubergphilis/letsencrypt#22]
i am getting the following ruby error with chef 12.3.0 -- am i missing something?
the certificate request seems to have worked as can be seen in the faraday client dump. (i removed sensitive data.)

```
================================================================================
      Error executing action `run` on resource 'ruby_block[create certificate for www.example.com]'
      ================================================================================

      NoMethodError
      -------------
      undefined method `file' for Chef::Resource::RubyBlock

      Cookbook Trace:
      ---------------
      /root/chef-solo/cookbooks-2/letsencrypt/providers/certificate.rb:104:in `block (3 levels) in class_from_file'

      Resource Declaration:
      ---------------------
      # In /root/chef-solo/cookbooks-2/letsencrypt/providers/certificate.rb

       96:     ruby_block "create certificate for #{new_resource.cn}" do
       97:       block do
       98:         if (all_validations.map { |authz| authz.status == 'valid' }).all?
       99:           begin
      100:             newcert = acme_cert(new_resource.cn, mykey, new_resource.alt_names)
      101:           rescue Acme::Client::Error => e
      102:             fail "[#{new_resource.cn}] Certificate request failed: #{e.message}"
      103:           else
      104:             file "#{new_resource.cn} SSL new crt" do
      105:               path    new_resource.crt || new_resource.fullchain
      106:               owner   new_resource.owner
      107:               group   new_resource.group
      108:               content new_resource.crt.nil? ? newcert.fullchain_to_pem : newcert.to_pem
      109:               mode    00644
      110:               action  :create
      111:             end
      112:
      113:             file "#{new_resource.cn} SSL new chain" do
      114:               path    new_resource.chain
      115:               owner   new_resource.owner
      116:               group   new_resource.group
      117:               content newcert.chain_to_pem
      118:               not_if  { new_resource.chain.nil? }
      119:               mode    00644
      120:               action  :create
      121:             end
      122:           end
      123:         else
      124:           fail "[#{new_resource.cn}] Validation failed, unable to request certificate"
      125:         end
      126:       end

      Compiled Resource:
      ------------------
      # Declared in /root/chef-solo/cookbooks-2/letsencrypt/providers/certificate.rb:96:in `block in class_from_file'

      ruby_block("create certificate for www.example.com") do
        action "run"
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        block_name "create certificate for www.example.com"
        declared_type :ruby_block
        cookbook_name :example
        block #<Proc:0x0000000886d7d0@/root/chef-solo/cookbooks-2/letsencrypt/providers/certificate.rb:97>
        client #<Acme::Client:0x000000088557c0 @directory_uri=nil, @private_key=#<OpenSSL::PKey::RSA:0x00000008855860>, @endpoint="https://acme-staging.api.letsencrypt.org", @nonces=[FILTERED], @operation_endpoints={"new-authz"=>"/acme/new-authz", "new-cert"=>"/acme/new-cert", "new-reg"=>"/acme/new-reg", "revoke-cert"=>"/acme/revoke-cert"}, @connection=#<Faraday::Connection:0x00000008855360 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.9.2"}, @params={}, @options=#<Faraday::RequestOptions (empty)>, @ssl=#<Faraday::SSLOptions verify=true>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x00000008854f50 @handlers=[Acme::Client::FaradayMiddleware, Faraday::Adapter::NetHttp], @app=#<Acme::Client::FaradayMiddleware:0x00000008854118 @app=#<Faraday::Adapter::NetHttp:0x00000008854168 @app=#<Proc:0x00000008854230@/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:152 (lambda)>>, @client=#<Acme::Client:0x000000088557c0 ...>, @env=#<Faraday::Env @method=:get @body=[FILTERED]
```

**Comment by glaszig** [comment]
is this even working for anyone? [afaik](https://tickets.opscode.com/browse/CHEF-2756), cannot be used via macro methods inside `ruby_block` [but rather](https://docs.chef.io/resource_ruby_block.html) class instances themselves, e.g., `Chef::Resource::File.new`.
