### ISSUE TITLE
Contact method  is not supported

### ISSUE THREAD

**Issue by obazoud** [schubergphilis/letsencrypt#3]
I try to use letsencrypt cookbook.
But I got the following error.
Any ideas ?

```    ================================================================================
    Error executing action `create` on resource 'letsencrypt_certificate[xxxxxxx]'
    ================================================================================
    
    Acme::Error::Malformed
    ----------------------
    Error creating new registration :: Contact method  is not supported
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/letsencrypt/libraries/acme.rb:40:in `acme_client'
    /var/chef/cache/cookbooks/letsencrypt/libraries/acme.rb:49:in `acme_authz'
    /var/chef/cache/cookbooks/letsencrypt/providers/certificate.rb:55:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/ogury-jira/recipes/default.rb
    
     21:   letsencrypt_certificate node['jira']['apache2']['virtual_host_name'] do
     22:     crt      "/etc/ssl/#{node['jira']['apache2']['virtual_host_name']}.crt"
     23:     key      "/etc/ssl/#{node['jira']['apache2']['virtual_host_name']}.key"
     24:     method   'http'
     25:     wwwroot  "#{node['jira']['install_path']}/atlassian-jira"
     26:     notifies :reload, 'service[apache2]'
     27:   end
     28: end
```

**Comment by obazoud** [comment]
I fogot to prefix contacts with ```mailto:```
