### ISSUE TITLE
Acme Client reports Malformed error - algorithm 'none' in JWS header not acceptable

### ISSUE THREAD

**Issue by phutchins** [schubergphilis/letsencrypt#36]
Acme::Client::Error::Malformed: algorithm 'none' in JWS header not acceptable

```
================================================================================
     Error executing action `create` on resource 'letsencrypt_certificate[run.storj.io]'
     ================================================================================

     Acme::Client::Error::Malformed
     ------------------------------
     algorithm 'none' in JWS header not acceptable

     Cookbook Trace:
     ---------------
     /var/chef/cache/cookbooks/letsencrypt/libraries/acme.rb:40:in `acme_client'
     /var/chef/cache/cookbooks/letsencrypt/libraries/acme.rb:49:in `acme_authz'
     /var/chef/cache/cookbooks/letsencrypt/providers/certificate.rb:54:in `block (2 levels) in class_from_file'
     /var/chef/cache/cookbooks/letsencrypt/providers/certificate.rb:53:in `map'
     /var/chef/cache/cookbooks/letsencrypt/providers/certificate.rb:53:in `block in class_from_file'
     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
```

Happy to provide more info if needed. I've been using this same setup to get my certs and it is now broken... I updated my letsencrypt cookbook to latest and berks installed and uploaded again to ensure I have latest from everywhere.

**Comment by pelletiermaxime** [comment]
See https://github.com/unixcharles/acme-client/issues/74 for the temp fix: hardcoding the json-jwt gem to 1.5.2.

**Comment by positively** [comment]
Hi folks! How can I fix this problem if I'm not using unixcharles/acme-client? how can I lock this gem or do something else to resolve this issue?

**Comment by positively** [comment]
I have read "that fcking manual" )) and learned that I can tell directly which gem I want to install. I added to ''cookbook/letsencrypt/default.rb'' this code:
```
chef_gem 'json-jwt' do
  action :install
  version '1.5.2'
end
``` 
But, what to do in future? I think that this is not elegant way to fix this problem.. What can you advise to do with this?

**Comment by thoutenbos** [comment]
For the final fix I'm waiting on a new release of the `acme-client` gem which should fix the dependency on `json-jwt`

**Comment by thoutenbos** [comment]
Released v1.0.1 with a hard dep on the `json-jwt` version

**Comment by obazoud** [comment]
Got same errors with vesion 1.0.2:

```
    ================================================================================
    Error executing action `create` on resource 'letsencrypt_certificate[xxx.xxx.xxx]'
    ================================================================================
    
    Acme::Client::Error::Malformed
    ------------------------------
    algorithm 'none' in JWS header not acceptable
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/letsencrypt/libraries/acme.rb:36:in `acme_client'
    /var/chef/cache/cookbooks/letsencrypt/libraries/acme.rb:45:in `acme_authz'
    /var/chef/cache/cookbooks/letsencrypt/providers/certificate.rb:54:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/letsencrypt/providers/certificate.rb:53:in `map'
    /var/chef/cache/cookbooks/letsencrypt/providers/certificate.rb:53:in `block in class_from_file'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
    
```

**Comment by openfirmware** [comment]
I had to login to the node and use omnibus-chef's embedded `gem` to force uninstall `json-jwt` and `acme-client`, and then the next client-client run would install the correct versions.
