### ISSUE TITLE
Invalid character in DNS name

### ISSUE THREAD

**Issue by slashmili** [schubergphilis/letsencrypt#46]
Hi,

I'm using version 1.0.3 and have a problem with creating certificate:

this is how I use this recipe : 
```
letsencrypt_certificate "kmspace cert" do
  alt_names ['console.k-m.space', 'devel.k-m.space']
  fullchain "/etc/ssl/k-m.space.crt"
  key       "/etc/ssl/k-m.space.key"
  chain     "/etc/ssl/k-m.space.pem"
  method    "http"
  wwwroot   "/var/www/letsencrypt/"
  notifies  :restart, "service[nginx]"
end
```

And the error is like this: 

```
   ================================================================================
    Error executing action `create` on resource 'letsencrypt_certificate[kmspace cert]'
    ================================================================================

    Acme::Client::Error::Malformed
    ------------------------------
    Invalid character in DNS name

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/letsencrypt/libraries/acme.rb:45:in `acme_authz'
    /var/chef/cache/cookbooks/letsencrypt/providers/certificate.rb:54:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/letsencrypt/providers/certificate.rb:53:in `map'
    /var/chef/cache/cookbooks/letsencrypt/providers/certificate.rb:53:in `block in class_from_file'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/kmspace_nginx/recipes/default.rb

     48: letsencrypt_certificate "kmspace cert" do
     49:   alt_names ['console.k-m.space', 'devel.k-m.space']
     50:   fullchain "/etc/ssl/k-m.space.crt"
     51:   key       "/etc/ssl/k-m.space.key"
     52:   chain     "/etc/ssl/k-m.space.pem"
     53:   method    "http"
     54:   wwwroot   "/var/www/letsencrypt/"
     55:   notifies  :restart, "service[nginx]"
     56: end
     57:


    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/kmspace_nginx/recipes/default.rb:48:in `from_file'

    letsencrypt_certificate("kmspace cert") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :letsencrypt_certificate
      cookbook_name "hmspace_nginx"
      recipe_name "default"
      alt_names ["console.k-m.space", "devel.k-m.space"]
      fullchain "/etc/ssl/k-m.space.crt"
      key "/etc/ssl/k-m.space.key"
      chain "/etc/ssl/k-m.space.pem"
      method "http"
      wwwroot "/var/www/letsencrypt/"
      cn "kmspace cert"
      owner "root"
      group "root"
    end
```

Any idea what goes wrong? I can see that `alt_names` has proper domain list

**Comment by thoutenbos** [comment]
You have to specify the certificate subject in the resource name. Since `kmspace cert` is not a valid domain is fails to request a certificate. The `alt_names` attribute is only of adding SAN names.

**Comment by slashmili** [comment]
Ow ok thanks!
